### ISSUE TITLE
You are trying to load a weight file containing 1 layers into a model with 99 layers

### ISSUE THREAD

**Issue by Achraf97-lab** [SHIDCenter/PathoNet#3]
Bonjour, après execution de demo.py avec le modèl pré-entrainé PathoNet.hdf5 j'ai l'erreur suivante:
in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 1 layers into a model with 99 layers.

**Comment by JiweiMaster** [comment]
I also had this problem

**Comment by Achraf97-lab** [comment]
vous travaillez avec le model pré-entrainé PathoNet.hdf5?

**Comment by JiweiMaster** [comment]
when I edit by_name=True
model.load_weights(pretrained_weights,by_name=True)
next,
I get the following error:

Traceback (most recent call last):
  File "evaluation.py", line 73, in <module>
    eval()
  File "evaluation.py", line 52, in eval
    pipeline=Pipeline(conf) 
  File "/remote-home/share/20-jiwei-20210240276/GithubProject/NewYolov5/PathoNet/PathoNet/pipeline.py", line 23, in __init__
    self.model=models.modelCreator(self.modelName,self.inputShape,self.classes,weights=self.weights)
  File "/remote-home/share/20-jiwei-20210240276/GithubProject/NewYolov5/PathoNet/PathoNet/models.py", line 713, in modelCreator
    model=PathoNet(input_size = inputShape, classes=classes,pretrained_weights = weights)
  File "/remote-home/share/20-jiwei-20210240276/GithubProject/NewYolov5/PathoNet/PathoNet/models.py", line 379, in PathoNet
    model.load_weights(pretrained_weights,by_name=True)
  File "/usr/local/miniconda3/envs/tensorflow1_13/lib/python3.7/site-packages/keras/engine/network.py", line 1163, in load_weights
    reshape=reshape)
  File "/usr/local/miniconda3/envs/tensorflow1_13/lib/python3.7/site-packages/keras/engine/saving.py", line 1115, in load_weights_from_hdf5_group_by_name
    reshape=reshape)
  File "/usr/local/miniconda3/envs/tensorflow1_13/lib/python3.7/site-packages/keras/engine/saving.py", line 800, in preprocess_weights_for_loading
    elif layer_weights_shape != weights[0].shape:
IndexError: list index out of range

**Comment by JiweiMaster** [comment]
the provided pretrained PathoNet.hdf5 used Keras == 2.3.1, so need to update version of Keras  which is Keras == 2.2.4 in the requirement.txt

**Comment by Achraf97-lab** [comment]
Does the model work for you? do you have the annotated image on exit

**Comment by Achraf97-lab** [comment]
j'ai installé la version keras==2.4.3 et tensorflow==2.5.0 mais ca marche pas le modele pour moi

**Comment by Farzin-Negahbani** [comment]
@JiweiMaster @Achraf97-lab Since we used multi-GPU, weights were incompatible for single GPU usage. Thanks for pointing out this issue. Now you can re-download the pre-trained weights and let us know the result.

**Comment by JiweiMaster** [comment]
I used the pretrain model: Pathonet.hdf5, but I can't repeat the result in the paper.
Class              Prec.      Rec.        F1
--------------  --------  --------  --------
Immunopositive  0.928997  0.682814  0.787105
Immunonegative  0.971342  0.226698  0.367603
Lymphocyte      0.252862  0.560551  0.348512
@Farzin-Negahbani

**Comment by Farzin-Negahbani** [comment]
@JiweiMaster This seems to be related to the thresholding values, so I'm closing this issue, and we can talk about it on the related issue [here](https://github.com/SHIDCenter/PathoNet/issues/4).
